pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'd3872678-8ff6-4de6-ab68-f63785c8a52a', 
                url: 'https://github.com/vamshireddy903/jenkins.git',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t vamshi589/cicd-e2e:${IMAGE_TAG} ./python-jenkins-argocd-k8s
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
               withCredentials([usernamePassword(credentialsId: '65a424f9-5f41-448d-90f2-7987c7e3ed0a', passwordVariable: 'DOCKER_PASSWD', usernameVariable: 'DOCKER_USERNAME')]) {
                   sh '''
                    echo "Logging into Docker Hub"
                    echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                    echo "Pushing Docker image"
                    docker push vamshi589/cicd-e2e:${IMAGE_TAG}
                   '''           
                }
            }
        }
        
        stage('Update K8S manifest & push to Repo') {
    steps {
        withCredentials([
            usernamePassword(
                credentialsId: 'd3872678-8ff6-4de6-ab68-f63785c8a52a',
                passwordVariable: 'GIT_PASSWORD',
                usernameVariable: 'GIT_USERNAME'
            )
        ]) {
            sh '''
                cat python-jenkins-argocd-k8s/deploy/deploy.yaml

                sed -i "s|image: .*|image: vamshi589/cicd-e2e:${BUILD_NUMBER}|" python-jenkins-argocd-k8s/deploy/deploy.yaml

                cat python-jenkins-argocd-k8s/deploy/deploy.yaml

                git add python-jenkins-argocd-k8s/deploy/deploy.yaml

                git commit -m "Updated deploy.yaml with build ${IMAGE_TAG}" || echo "No changes to commit"

                git remote -v

                git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/vamshireddy903/jenkins.git HEAD:main
            '''
        }
    }
}
         stage('Deployment to K8s'){
           steps {
               withCredentials([file(credentialsId: '65a5a0a2-b78e-439a-b8b8-988601be7790', variable: 'KUBECONFIG')]) 
               {
                   sh '''
                   kubectl get nodes
                   kubectl apply -f python-jenkins-argocd-k8s/deploy/deploy.yaml
                  kubectl apply -f python-jenkins-argocd-k8s/deploy/service.yaml
                '''
               }
           }
        }
    }
}
        
