pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', 
                url: 'https://github.com/vamshireddy903/jenkins.git',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t vamshi589/cicd-e2e:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push vamshi589/cicd-e2e:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', 
                url: 'https://github.com/vamshireddy903/jenkins.git',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        cat deploy/deploy.yaml
                        sed -i "s|image: .*|image: vamshi589/cicd-e2e:${BUILD_NUMBER}|" deploy/deploy.yaml
                        cat deploy/deploy.yaml
                        git add deploy/deploy.yaml
                        git commit -m "Updated deploy.yaml with build ${BUILD_NUMBER}" || echo "No changes to commit"
                        git remote -v
                        git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/vamshireddy903/jenkins.git HEAD:main
                        '''                        
                    }
                }
            }
        }
    }
}
