pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: '233148ec-6b69-49db-8cf9-1d1e01b36bc0', 
                url: 'https://github.com/vamshireddy903/jenkins.git',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t vamshi589/cicd-e2e:${IMAGE_TAG} ./python-jenkins-argocd-k8s
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
               withCredentials([usernamePassword(credentialsId: 'f3db709f-b54a-4cb0-8fcb-018e0e679f62', passwordVariable: 'DOCKER_PASSWD', usernameVariable: 'DOCKER_USERNAME')]) {
                   sh '''
                    echo "Logging into Docker Hub"
                    echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                    echo "Pushing Docker image"
                    docker push vamshi589/cicd-e2e:${IMAGE_TAG}
                   '''           
                }
            }
        }
        
        stage('Update K8S manifest & push to Repo') {
    steps {
        withCredentials([
            usernamePassword(
                credentialsId: '233148ec-6b69-49db-8cf9-1d1e01b36bc0',
                passwordVariable: 'GIT_PASSWORD',
                usernameVariable: 'GIT_USERNAME'
            )
        ]) {
            sh '''
                cat python-jenkins-argocd-k8s/deploy/deploy.yaml

                sed -i "s|image: .*|image: vamshi589/cicd-e2e:${BUILD_NUMBER}|" python-jenkins-argocd-k8s/deploy/deploy.yaml

                cat python-jenkins-argocd-k8s/deploy/deploy.yaml

                git add python-jenkins-argocd-k8s/deploy/deploy.yaml

                git commit -m "Updated deploy.yaml with build ${IMAGE_TAG}" || echo "No changes to commit"

                git remote -v

                git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/vamshireddy903/jenkins.git HEAD:main
            '''
        }
    }
}
    }
}
        
