pipeline {
  agent any
  stages {
    stage('Start Back-end') {
      steps {
        sh '''
          docker rm -f my-backend || true
          docker run -d --name my-backend maven:3.8.1-adoptopenjdk-11 tail -f /dev/null
        '''
      }
    }
    stage('Start Front-end') {
      steps {
        sh '''
          docker rm -f my-frontend || true
          docker run -d --name my-frontend node:16-alpine tail -f /dev/null
        '''
      }
    }
    stage('Check containers') {
      steps {
        sh 'docker ps'
      }
    }
  }
}
