pipeline {
  agent any
  stages {
    stage('Start Back-end') {
      steps {
        script {
          docker.image('maven:3.8.1-adoptopenjdk-11').run('-d --name my-backend')
        }
      }
    }
    stage('Start Front-end') {
      steps {
        script {
          docker.image('node:16-alpine').run('-d --name my-frontend')
        }
      }
    }
  }
}
